# This file was generated by GoReleaser. DO NOT EDIT.
class OtDockerLinter < Formula
  desc "A linter designed in golang for checking Dockerfile best practices."
  homepage "https://github.com/opstree/OT-DockerLinter"
  version "0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.2/ot-docker-linter_0.2_macos-64bit.tar.gz"
    sha256 "743d38c004f069aff96f0f03598f54556ed9ec500385a49003ebb06c57c65cf1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.2/ot-docker-linter_0.2_linux-64bit.tar.gz"
      sha256 "5cedf5e0d6db46c6a2f006bfacfed6bd3f01e6ea303a4a8a2f5538188bd14137"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.2/ot-docker-linter_0.2_linux-arm64.tar.gz"
        sha256 "13146cd2b1327359dce2d7623b2d7094dde8a82af2e91287d917d08056b4a6d2"
      else
      end
    end
  end

  def install
    bin.install "ot-docker-linter"
  end

  test do
    system "#{bin}/program --version"
  end
end
