# This file was generated by GoReleaser. DO NOT EDIT.
class OtDockerLinter < Formula
  desc "A linter designed in golang for checking Dockerfile best practices."
  homepage "https://github.com/opstree/OT-DockerLinter"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.1/ot-docker-linter_0.1_macOS-64bit.tar.gz"
    sha256 "5451a1b4ef1c88f1b7f301fb92f26488ac89614cefa63f883c8255f81b5cdcd1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.1/ot-docker-linter_0.1_Linux-64bit.tar.gz"
      sha256 "ac6b79a7070ed2293aec6011be480f0336b1fb2282836fe0d48a607802c8ec95"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opstree/OT-DockerLinter/releases/download/v0.1/ot-docker-linter_0.1_Linux-ARM64.tar.gz"
        sha256 "d46208e5fc11ef347676a5deca41b119872bedffbec3d36dbe4c730c6403c40e"
      else
      end
    end
  end

  def install
    bin.install "ot-docker-linter"
  end

  test do
    system "#{bin}/program --version"
  end
end
