# This file was generated by GoReleaser. DO NOT EDIT.
class RedisMigrator < Formula
  desc "A tool designed in golang for migrating redis keys."
  homepage "https://github.com/opstree/redis-migration"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/opstree/redis-migration/releases/download/v0.1/redis-migrator_0.1_macos-64bit.tar.gz"
    sha256 "83ee75a37e60a9d77eb3fab54303ccd3c51c0f6f6464ea084f85daa66bf7eceb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/opstree/redis-migration/releases/download/v0.1/redis-migrator_0.1_linux-64bit.tar.gz"
      sha256 "fd92b4d2cc457bfc83eed0eb37251f64a0adeb3d24cdea178682af7160c951b8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opstree/redis-migration/releases/download/v0.1/redis-migrator_0.1_linux-arm64.tar.gz"
        sha256 "e042787c31c809406c482ca0bd5cf4125647a97d45da58f11c3594e517285c10"
      else
      end
    end
  end

  def install
    bin.install "redis-migrator"
  end

  test do
    system "#{bin}/program version"
  end
end
